FROM python:3.13.5-slim
WORKDIR /config
COPY requirement.txt .
RUN pip install -r requirement.txt
COPY . .
EXPOSE 8000
CMD ["gunicorn","config.wsgi:application","--bind","0.0.0.0:8000","--workers","4"]
