name: Test Pipeline 
on: 
  push:
jobs:
  test-backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env: 
          POSTGRES_USER: test_user
          POSTGRES_DB: erp
          POSTGRES_PASSWORD: 123456
        
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: setup python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.13.5"
      
      - name: install dependencies
        run: pip install -r Backend/requirement.txt
      
      - name: run tests
        env: 
          DATABASE_URL: postgresql://test_user:123456@localhost:5432/erp
          DEBUG: 'True'
          ALLOWED_HOST: '*'
        run: |
          cd Backend 
          python manage.py test
  
  build-and-push-image:
    needs: test-backend
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: creating multiarch builder
        run: docker buildx create --name multiarch --driver docker-container --bootstrap
      
      - name: using mulitarch builder as default
        run: docker buildx use multiarch

      - name: checkout repo
        uses: actions/checkout@v4

      - name: build image
        run: docker buildx build --platform linux/arm64 -t ghcr.io/mk-debugger11/erp:${{ github.sha }} ./Backend --push

      # - name: push image
      #   run: docker push ghcr.io/mk-debugger11/erp:${{ github.sha }}
  deploy:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: connect to tailscale 
        uses: tailscale/github-action@v4
        with: 
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      # - name: Setup SSH
      #   uses: webfactory/ssh-agent@v0.9.1
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      # - name: ssh-to-vm
      #   run: |
      #     ssh -T -o ConnectTimeout=10 -o BatchMode=yes mukulmac@100.127.19.53 "whoami"
      - name: ssh to vm
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.TAILSCALE_IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /home/mukulmac/ERP \
            docker compose up