name: Test Pipeline 
on: 
  push:
jobs:
  test-backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env: 
          POSTGRES_USER: test_user
          POSTGRES_DB: erp
          POSTGRES_PASSWORD: 123456
        
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: setup python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.13.5"
      
      - name: install dependencies
        run: pip install -r Backend/requirement.txt
      
      - name: run tests
        env: 
          DATABASE_URL: postgresql://test_user:123456@localhost:5432/erp
          DEBUG: 'True'
          ALLOWED_HOST: '*'
        run: |
          cd Backend 
          python manage.py test
  
  build-image:
    needs: test-backend
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: build image
        run: docker build -t erp ./Backend